name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3 # Using v3 as it's the latest
      with:
        api-level: 34 # Assuming API level 34, adjust if needed
        build-tools-version: 34.0.0 # Assuming build tools 34.0.0
        ndk-version: 25.1.8937393 # Optional: specify NDK version if needed
        # cmake-version: # Optional: specify CMake version if needed

    - name: Grant execute permission to gradlew
      run: chmod +x ai-catalog/gradlew

    - name: Build with Gradle
      working-directory: ./ai-catalog
      run: ./gradlew build

    - name: Run Android Instrumented Tests
      working-directory: ./ai-catalog
      run: ./gradlew :app:connectedAndroidTest
